### ISSUE TITLE
Beautiful Soup Fails with Error

### ISSUE THREAD

**Issue by g33k247** [yassineaboukir/Asnlookup#1]
During install, I see:

Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.20.1)
Collecting BeautifulSoup (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nvbun87p/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nvbun87p/BeautifulSoup/

**Comment by yassineaboukir** [comment]
Can you clone again the repo and try to re-install?
