### ISSUE TITLE
We couldn't connect to asnlookup.com API. Try again!

### ISSUE THREAD

**Issue by MateorChan** [yassineaboukir/Asnlookup#14]
Something wrong...

Console Error:
We couldn't connect to asnlookup.com API. Try again!

**Comment by yassineaboukir** [comment]
Fixed now. Thanks!

**Comment by shreerammallick** [comment]
We couldn't connect to asnlookup.com API. Try again!

**Comment by yassineaboukir** [comment]
@shreerammallick fixed, thanks!

**Comment by Almahdi8** [comment]
!] We couldn't connect to asnlookup.com API. Try again!

**Comment by ARTP3R** [comment]
[!] We couldn't connect to asnlookup.com API. Try again!

**Comment by ARTP3R** [comment]
Solved after check https://asnlookup.com/apidocs/
![image](https://user-images.githubusercontent.com/77728050/170669045-d1bde508-22bf-48f2-b0aa-928d32f8921b.png)

**Comment by elsherifX00** [comment]
[!] We couldn't connect to asnlookup.com API. Try again!

**Comment by kameshwadhai** [comment]
[!] We couldn't connect to asnlookup.com API. Try again!
