### ISSUE TITLE
error when i run tool 

### ISSUE THREAD

**Issue by prosecurity** [yassineaboukir/Asnlookup#6]
____ ____ _  _ _    ____ ____ _  _ _  _ ___
        |__| [__  |\ | |    |  | |  | |_/  |  | |__]
        |  | ___] | \| |___ |__| |__| | \_ |__| |

         Author: Yassine Aboukir (@yassineaboukir)

Traceback (most recent call last):
  File "asnlookup.py", line 174, in <module>
    download_db()
  File "asnlookup.py", line 59, in download_db
    with open("filesize.txt", "r") as filesize:
IOError: [Errno 2] No such file or directory: 'filesize.txt'

**Comment by yassineaboukir** [comment]
Hi,

This was fixed.

Regards.
