### ISSUE TITLE
Public database is not available anymore

### ISSUE THREAD

**Issue by abdilahrf** [yassineaboukir/Asnlookup#7]
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

Maxmind made changes to their database public access

**Comment by yassineaboukir** [comment]
Hey!

Thanks for reporting! The issue has been fixed a few days ago but the tool now requires signing up for an account on Maxmind. Check readme page :)

Thanks!

**Comment by abdilahrf** [comment]
My bad, i have not check the latest version 

Thanks @yassineaboukir !
