### ISSUE TITLE
Error: couldn't connect to asnlookup.com API !

### ISSUE THREAD

**Issue by Xeek3y** [yassineaboukir/Asnlookup#8]
Hello i'm trying to run this script and before python2 i tried this tool with python3 but it's giving me this error:
We couldn't connect to asnlookup.com API. Try again!

So i tried with python2 and the tools sometime works and sometime not nad mostly not! Getting the same error in python2 as python3:
Error:
We couldn't connect to asnlookup.com API. Try again!

**Comment by yassineaboukir** [comment]
Hi - thanks a lot for reporting. I'll investigate and get back to you!

**Comment by yassineaboukir** [comment]
It should work fine now. Thanks!

**Comment by avee0** [comment]
hey i m facing this error please help

**Comment by yassineaboukir** [comment]
should work now @avee0 @avee0

**Comment by avee0** [comment]
yup working thanks  man @yassineaboukir
