### ISSUE TITLE
Incorrect results for searching "linkedin"

### ISSUE THREAD

**Issue by fedyakov** [yassineaboukir/Asnlookup#9]
When I request "linkedin" I get many irrelevant IP blocks.
F.e. I've got 185.146.208.0/22 and other blocks from AS134431, which is "News and Entertainment Network Corp", not LinkedIn.

**Comment by yassineaboukir** [comment]
Hi,

Let me look into this.

Thanks for reporting!

**Comment by yassineaboukir** [comment]
Hi @fedyakov,

The issue is now resolved and this was a an important bug to fix. Thank you very much for flagging this behavior!

Regards.
